env: dev
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dborder?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
server:
  port: 8062
mybatis:
  type-aliases-package: com.lf.order.domain
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 设置ribbon负载均衡规则
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
